api:
  ib_host: "127.0.0.1"
  ib_port: 7497        # 7496 = Live / 7497 = Paper
  ib_client_id: 1
db:
  path: "data/db/market.db"
param:
  host: "127.0.0.1"
  port: 1111
dash:
  host: "127.0.0.1"
  port: 2222